Deductibles and reinsurance
==================

## Introduction


In this chapter, we will introduce the concept of risk-sharing. We will
consider two types of risk-sharing including deductibles and
reinsurance. The purpose of risk sharing is to spread the risk among the
parties involved. For example,

1.  A policyholder purchases automobile insurance with a deductible. The
    policyholder is responsible for some of the risk , and transfer the
    larger portion of the risk to the insurer. The policyholder will
    submit a claim when the loss exceeds the deductible.

2.  A direct insurer can pass on some of the risks to another insurance
    company known as a reinsurer by purchasing insurance from the
    reinsurer. It will protect the insurer from paying large claims.

The main goals of the chapter include the derivation of the distribution
and corresponding moments of the claim amounts paid by the policyholder,
direct insurer and the reinsurer in the presence of risk-sharing
arrangements. In addition, the effects of risk-sharing arrangements will
reduce the mean and variability of the amount paid by the direct
insurer, and also the probability that the insurer will be involved on
very large claims.

## Deductibles


The insurer can modify the policy so that the policyholder is
responsible for some of the risk by including a deductible (also known
as policy excess).

Given a financial loss of $X$ and a deductible of $d$,

-   the insured agrees to bear the first amount of $d$ of any loss $X$,
    and only submits a claim when $X$ exceeds $d$.

-   the insurer will pay the remaining of $X - d$ if the loss $X$
    exceeds $d$.

For example, suppose a policy has a deductible of 1000, and you incur a loss
of 3000 in a car accident. You pay the deductible of 1000 and the car insurance
company pays the remaining of 2000.

Let $X$ be the claim amount, $V$ and $Y$ the amounts of the claim paid
by the policyholder, the (direct) insurer, respectively, i.e.
$$X = V + Y.$$ So the amount paid by the policyholder and the insurer
are given by

$$\begin{aligned}
    V = 
    \begin{cases}
        X &\text{if }  X \le d\\   
        d &\text{if }  X > d,
    \end{cases} \\
    Y = 
    \begin{cases}
        0 &\text{if }  X \le d\\   
        X - d &\text{if }  X > d.
    \end{cases}\end{aligned}$$ The amounts $V$ and $Y$ can also be
expressed as $$V = \min(X,d), \quad Y = \max(0,X-d).$$

The relationship between the policyholder and insurer is similar to that
between the insurer and reinsurer. Therefore, the detailed analysis of a
policy with a deductible is analogous to reinsurance, which will be
discussed in the following section.

## Reinsurance


Reinsurance is insurance purchased by an insurance company in order to
protect itself from large claims. There are two main types of
reinsurance arrangement:

1.  excess of loss reinsurance; and

2.  proportional reinsurance.

Excess of loss reinsurance
--------------------------

Under excess of loss reinsurance arrangement, the direct insurer sets a
certain limit called a retention level $M >0$. For a claim $X$,

-   the insurance company pays any claim in full if $X \le M$; and

-   the reinsurer (or reinsurance company) pays the remaining amount of
    $X - M$ if $X > M$.

The position of the reinsurer under excess of loss reinsurance is the
same as that of the insurer for a policy with a deductible.

Let $X$ be the claim amount, $V, Y$ and $Z$ the amounts of the claim
paid by the policyholder, (direct) insurer and reinsurer, respectively,
i.e. $$X = V + Y + Z.$$ In what follows, without stated otherwise, we
consider the case in which there is no deductible in place, i.e. $V = 0$
and $$X = Y + Z.$$ So the amount paid by the direct insurer and the
reinsurer are given by

$$\begin{aligned}
    Y = 
    \begin{cases}
        X &\text{if }  X \le M\\   
        M &\text{if }  X > M,
    \end{cases} \\
    Z = 
    \begin{cases}
        0 &\text{if }  X \le M\\   
        X - M &\text{if }  X > M.
    \end{cases}\end{aligned}$$ The amounts $Y$ and $Z$ can also be
expressed as $$Y = \min(X,M), \quad Z = \max(0,X-M).$$

d = 1000 M = 10000 X = \[3000, 800, 25000, 5000, 20000\]

::: {.example #examplePayouts}
Suppose a policy has a deductible of 1000 and the
insurer arrange excess of loss reinsurance with retention level of 10000. A
sample of loss amounts in one year consists of the following values, in
unit of Thai baht: $$3000, 800, 25000, 5000, 20000 .$$ Calculate the
total amount paid by:*

1.  *the policyholder;*

2.  *the insurer; and*

3.  *the reinsurer.*
:::

**Solution:**

The total amounts paid by

-   the policyholders : $$1000 + 800 + 1000 + 1000 + 1000 = 4800.$$

-   The insurer : $$2000 + 0 + 10000 + 4000 + 10000 = 26000.$$

-   The reinsurer : $$0 + 0 + 14000 + 0 + 9000 = 23000.$$

Mixed distributions
-------------------

In the subsequent sections, we will derive the probability distribution
of the random variables $Y$ and $Z$, which are the insurer's and
reinsurer's payouts on claims. Their distributions are neither purely
continuous, nor purely discrete. First we start with some important
properties of such random variables.

A random variable $U$ which is partly discrete and partly continuous is
said to be a mixed distribution. The distribution function of $U$,
denoted by $F_U(x)$ is continuous and differentiable except for some
values of $x$ in a countable set $S$. For a mixed distribution $U$,
there exists a function $f_U(x)$ such that
$$F_U(x) = \Pr(U \le x) = \int_{-\infty}^x f_U(x) dx + \sum_{x_i \in S, x_i \le x } \Pr(U = x_i).$$
The expected value of $g(U)$ for some function $g$ is given by

\begin{equation} 
(\#eq:eqnExpectationMixed) \mathrm{E}[g(U)] = \int_{-\infty}^\infty g(x) f_U(x) \mathop{}\!d{x} + \sum_{x_i \in S } g(x_i) \Pr(U = x_i).
\end{equation}

It is the sum of the integral over the intervals at which $f_U(x)$ is
continuous and the summation over the points in $S$.

The function $f_U(x)$ is not the probability density function of $U$
because $\int_{-\infty}^\infty f_U(x) dx \neq 1$. In particular, it is
the derivative of $F_U(x)$ at the points where $F_U(x)$ is continuous
and differentiable.

Recall that $X$ denotes the claim amount and $Y$ and $Z$ be the amounts
of the claim paid by the insurer and reinsurer. The distribution
function and the density function of the claim amount $X$ are denoted by
$F_{X}$ and $f_X(x)$, where we assume that $X$ is continuous. In the
following examples, we will derive the distribution, mean and variance
of the random variables $Y$ and $Z$. Furthermore, both random variables
$Y$ and $Z$ are examples of mixed distributions.

::: {.example}
*Let $F_Y$ denote the distribution function of
$Y = \min(X,M)$. It follows that $$F_Y(x) = 
    \begin{cases}
        F_X(x) &\text{if }  x < M\\   
        1 &\text{if }  x \ge M
    \end{cases}.$$ Hence, the distribution function of $Y$ is said to be
a mixed distribution.*
:::

**Solution:**
From $Y = \min(X,M)$, if $y < M$, then
$$F_Y(y) = \Pr(Y \le y) = \Pr(X \le y) = F_X(y).$$ If $y \ge M$, then
$$F_Y(y) = \Pr(Y \le y) = 1,$$ which follows because $\min(X,M) \le M$.

Hence, $Y$ is mixed with a density function $f_X(x)$, for $0 \le x < M$
and a mass of probability at $M$, with $Pr(Y = M) = 1 - F_X(M)$. The
last equality follows from $$\begin{aligned}
    \Pr(Y = M) &= \Pr(X > M) \\
        &=   1 - \Pr(X \le M) = 1 - F_X(M). \end{aligned}$$

::: {.example}
*Show that
$$\mathrm{E}[Y] = \mathrm{E}[\min(X,M)] = \mathrm{E}[X] - \int_0^\infty y f_X(y+M) \mathop{}\!dy.$$*
:::

$\mathrm{E}[Y]$ is the expected payout by the insurer.


$$\begin{aligned}
    \mathrm{E}[Y] &= \mathrm{E}[\min(X,M)] \\
        &= \int_0^\infty \min(X,M) \cdot f_X(x) \, dx \\
        &= \int_0^M x \cdot f_X(x) \, dx + \int_M^\infty M \cdot f_X(x) \, dx \\
        &= \int_0^M x \cdot f_X(x) \, dx + \int_M^\infty x \cdot f_X(x) \, dx + \int_M^\infty (M - x) \cdot f_X(x) \, dx \\
        &= \mathrm{E}[X] + \int_M^\infty (M - x) \cdot f_X(x) \, dx \\
    &= \mathrm{E}[X] + \int_0^\infty (-y) \cdot f_X(y+M) \, dy \\
    &=  \mathrm{E}[X] - \int_0^\infty y \cdot f_X(y+M) \, dy 
\end{aligned}$$

**Note**
Under excess of loss reinsurance arrangement, the mean amount paid by
the insurer is reduced by the amount equal to
$\int_0^\infty y f_X(y+M) \mathop{}\!dy.$

::: {.example}
*Let $X$ be an exponential distribution with parameter
$\lambda$ and $Y = \min(X,M)$. Then $$F_Y(x) = 
    \begin{cases}
        1 - e^{-\lambda x} &\text{if }  x < M\\   
        1 &\text{if }  x \ge M
    \end{cases}.$$ A plot of the distribution function $F_Y$ is given in
Figure [1](#figMixedDist){reference-type="ref"
reference="figMixedDist"}. Hence, $Y$ is a mixed distribution with a
density function $f_Y(x) = f_X(x)$ for $0 < x < M$ and a probability
mass at $M$ is $\Pr(Y = M) = 1 - F_X(M)$.*

Using
\@ref(eq:eqnExpectationMixed), the expected value of $Y$,
$\mathrm{E}[Y]$ is given by 

$$\begin{aligned}
    \mathrm{E}[Y] &= \int_{0}^M x f_X(x) \mathop{}\!d{x}  + M(1 - F_X(M)).  \end{aligned}$$
:::

<!-- ![[\[figMixedDist\]]{#figMixedDist label="figMixedDist"} The -->
<!-- distribution function $F_Y(x)$ with $\lambda = 1$ and -->
<!-- $M = 2$.](mixed.pdf){#figMixedDist} -->

::: {.example}
*Let $F_Z$ denote the distribution function of
$Z = \max(0,X-M)$. It follows that $$F_Z(x) = 
    \begin{cases}
        F_{X}(M) &\text{if }  x = 0\\   
        F_{X}(x + M) &\text{if }  x > 0
    \end{cases}.$$ Hence, the distribution function of $Z$ is a mixed
distribution with a mass of probability at $0$.*
:::

**Solution:**
The random variable $Z$ is the **reinsurer's payout** which also include
**zero claims**. Later we will consider only **reinsurance claims**,
which involve the reinsurer, i.e. claims such that $X > M$.

The distribution of $Z$ can be derived as follows:

-   For $x =0$, $$F_Z(0) = \Pr(Z = 0) = \Pr(X \le M) = F_X(M).$$

-   For $x > 0$, $$\begin{aligned}
        F_Z(0) &= \Pr(Z \le x) = \Pr(\max(0,X-M) \le x) \\
        &= \Pr(X- M \le x) = \Pr(X \le x + M) = F_X(x + M).\end{aligned}$$

::: {.example}
*Let $X$ be an exponential distribution with parameter
$\lambda$ and $Z = \max(0,X-M)$. Derive and plot the probability
distribution $F_Z$ for $\lambda = 1$ and $M = 2$.*
:::

::: {.example}
*Show that
$$\mathrm{E}[Z] = \mathrm{E}[\max(0,X-M)] = \int_M^\infty (x- M) f_X(x) \mathop{}\!dx = \int_0^\infty y f_X(y+M) \mathop{}\!dy.$$
Comment on the result.*
:::
**Solution:**
The expected payout on the claim by the reinsurer, $\mathrm{E}[Z]$, and
can also be found directly as follows: $$\begin{aligned}
\mathrm{E}[Z] &= \mathrm{E}[\max(0,X-M)] \\
    &= \int_0^M 0 \cdot f_X(x) \, dx + \int_M^\infty (X-M) \cdot f_X(x) \, dx \\
    &= 0 +  \int_0^\infty y \cdot f_X(y + M) \, dy.\end{aligned}$$ It
follows from the previous results that
$$\mathrm{E}[X] = \mathrm{E}[Y + Z] =  \mathrm{E}[Y]+ \mathrm{E}[Z].$$


::: {.example}
*Let the claim amount $X$ have exponential distribution
with mean $\mu = 1/\lambda$.*

1.  *Find the proportion of claims which involve the reinsurer.*

2.  *Find the insurer's expected payout on a claim.*

3.  *Find the reinsurer's expected payout on a claim.*
:::

**Solution:**
1.  The proportion of claims which involve the reinsurer is
    $$\Pr(X > M) = 1 - F_X(M) = e^{-\lambda M} = e^{-M/\mu}.$$

2.  The insurer's expected payout on a claim can be calculated by
    $$\begin{aligned}
        \mathrm{E}[Y] &= \mathrm{E}[X] -  \int_0^\infty y \cdot \lambda e^{-\lambda(y+M)} \, dy \\
            &= \mathrm{E}[X] - e^{-\lambda M} \int_0^\infty y \cdot \lambda e^{-\lambda \cdot y} \, dy \\
            &= \mathrm{E}[X] - e^{-\lambda M}  \mathrm{E}[X] \\
            &= (1 - e^{-\lambda M})  \mathrm{E}[X].\end{aligned}$$

3.  It follows from the above result that the reinsurer's expected
    payout on a claim is $e^{-\lambda M} \mathrm{E}[X].$

::: {.example}
*An insurer covers an individual loss $X$ with excess of
loss reinsurance with retention level $M$. Let $f_X(x)$ and $F_X(x)$
denote the pdf and cdf of $X$, respectively.*

1.  *Show that the variance of the amount paid by the insurer on a
    single claim satisfies:
    $$\mathrm{Var}[\min(X,M)] = \int_0^M x^2 f_X(x) \mathop{}\!dx + M^2 (1 - F_X(M)) - (\mathrm{E}[\min(X,M)])^2.$$*

2.  *Show that the variance of the amount paid by the reinsurer on a
    single claim satisfies:
    $$\mathrm{Var}[\max(0,X-M)] = \int_M^\infty (x-M)^2 f_X(x) \mathop{}\!dx  - (\mathrm{E}[\max(0,X-M)])^2.$$*
:::

The distribution of reinsurance claims
--------------------------------------

In practice, the reinsurer involves only claims which exceed the
retention limit, i.e. $X > M$. Information of claims which are less or
equal to $M$ may not be available to the reinsurer. The claim amount $Z$
paid by the reinsurer can be modified accordingly to take into account
of non-zero claim sizes.

Recall from
Example \@ref(exm:examplePayouts), there are only three claims whose amounts
exceed the retention level of . Such claims, consisting of , 9000 and
23000 which involves the reinsurer are known as **reinsurance claims**.

Let $W = Z|Z>0$ be a random variable representing the amount of a
non-zero payment by the reinsurer on a reinsurance claim. The
distribution and density of $W$ can be calculated as follows: for
$x > 0$, $$\begin{aligned}
     \Pr[W \le x ] &= \Pr[Z \le x | Z >0] \\
            &= \Pr[X - M \le x | X > M] \\
            &= \frac{\Pr[M < X \le x + M]}{\Pr[X > M]}\\
            &= \frac{F_X(x+M) - F_X(M)}{1-F_X(M)}.\end{aligned}$$
Differentiating with respect to $x$, we obtain the density function of
$W$ as $$f_W(x) = \frac{f_X(x+M)}{1 - F_X(M)}.$$ Hence, the mean and
variance can be directly obtained from the density function of $W$.

Proportional reinsurance
------------------------

Under excess of loss reinsurance arrangement, the direct insurer pays a
fixed proportion $\alpha$, called the proportion of the risk retained by
the insurer, and the reinsurer pays the remainder of the claim.

Let $X$ be the claim amount, $Y$ and $Z$ the amounts of the claim paid
by the policyholder, (direct) insurer and reinsurer, respectively, i.e.
$$X = Y + Z.$$ So the amount paid by the direct insurer and the
reinsurer are given by $$Y = \alpha X, \quad Z = (1 - \alpha) X.$$ Both
of the random variables are scaled by the factor of $\alpha$ and
$1- \alpha$, respectively.

::: {.example}
*Derive the distribution function and density function
of $Y$.*
:::
**Solution:**
Let $X$ has a distribution function $F$ with density function $f$. The
distribution function of $Y$ is given by $$\Pr(Y \le x) = F(x/a).$$
Hence, the density function is $$f_Y(x) = \frac{1}{a}f(x/a).$$

You can get more examples from Tutorials.
